### PR TITLE
Gaming glossary

### PR DESCRIPTION
**Pull request by TechWriterMelissa**

### CODE REVIEW

**Review by Laura-Novich-OBW — COMMENTED** [review]
Really good start!
You are almost there:
You need to add to your letters at the top some non breaking spaces - for example:
&nbsp; 
Also your html has a lot of spaces which is not necessary.
Did you check that the links from the top work?

**Comment by TechWriterMelissa** [comment]
Great, thank you, will make those changes. Yes, I did check the links.

**Review by Laura-Novich-OBW — APPROVED** [review]
Looks great!

**Comment by Laura-Novich-OBW** [comment]
please add a screenshot of this page to Google Classroom!

**Pull request merged**
